Cypress.Commands.add('adicionaProdutos', (tamanho, cor, quantidade) => {
    cy.get('.search').should('be.visible')
    .type('Abominable Hoodie', { delay: 50 })
    cy.get('.search > .tbay-search-form > .form-ajax-search > .form-group > .input-group > .button-group')
    .click()
    cy.get('.product_title').should('be.visible')
    cy.get('.button-variable-item-' + tamanho).click()
    cy.get('.button-variable-item-' + cor).click()
    cy.get('.input-text').clear().type(quantidade)
    cy.get('.single_add_to_cart_button').click()
    cy.get('.woocommerce-message').should('contain', '“Abominable Hoodie” foi adicionado no seu carrinho.')

    cy.get('.search').should('be.visible')
    .type('Stellar Solar Jacket', { delay: 50 })
    cy.get('.search > .tbay-search-form > .form-ajax-search > .form-group > .input-group > .button-group')
    .click()
    cy.get('.product_title').should('be.visible')
    cy.get('.button-variable-item-' + tamanho).click()
    cy.get('.button-variable-item-' + cor).click()
    cy.get('.input-text').clear().type(quantidade)
    cy.get('.single_add_to_cart_button').click()
    cy.get('.woocommerce-message').should('contain', '“Stellar Solar Jacket” foi adicionado no seu carrinho.')

    cy.get('.search').should('be.visible')
    .type('Ingrid Running Jacket', { delay: 50 })
    cy.get('.search > .tbay-search-form > .form-ajax-search > .form-group > .input-group > .button-group')
    .click()
    cy.get('.product_title').should('be.visible')
    cy.get('.button-variable-item-' + tamanho).click()
    cy.get('.button-variable-item-' + 'Red').click()
    cy.get('.input-text').clear().type(quantidade)
    cy.get('.single_add_to_cart_button').click()
    cy.get('.woocommerce-message').should('contain', '“Ingrid Running Jacket” foi adicionado no seu carrinho.')
    cy.log('Produtos Adicionados com sucesso!')
})

